AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket with configurable name and versioning'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
    Default: my-codepipeline-bucket
    AllowedPattern: ^[a-z0-9][a-z0-9-]*[a-z0-9]$
    ConstraintDescription: Bucket name must be lowercase, alphanumeric, and hyphens only
    MinLength: 3
    MaxLength: 63
    
  VersioningStatus:
    Type: String
    Description: Enable or suspend versioning on the S3 bucket
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended
    ConstraintDescription: Must be either Enabled or Suspended

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: !Ref VersioningStatus
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Purpose
          Value: CodePipeline-Lab
        - Key: Environment
          Value: Development

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
      
  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"
      
  VersioningStatus:
    Description: Versioning status of the S3 bucket
    Value: !Ref VersioningStatus
    Export:
      Name: !Sub "${AWS::StackName}-VersioningStatus"